import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { SITE_HOST } from "../src/utils/constants";
import {
   encodeIdForUrl,
   findDuplicateLabels,
   getDisplayLabel,
   safeFileName,
} from "../src/utils/monumentFormatters";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const HOST = SITE_HOST;
const DIST_DIR = path.join(__dirname, "../dist");
const GEOJSON_PATH = path.join(__dirname, "../data/monuments.geojson");
const MONUMENT_DIR = path.join(DIST_DIR, "monument");
const SITEMAP_PATH = path.join(DIST_DIR, "sitemap.xml");
const ROBOTS_PATH = path.join(DIST_DIR, "robots.txt");
// Generated by scripts/prerender.ts; consumed via include in nginx.conf.
const REDIRECTS_PATH = path.join(__dirname, "..", "monument-redirects.conf");
const NGINX_CONF_PATH = path.join(__dirname, "../nginx.conf");

const SITE_TITLE = "Viki Abidələri Sevir Azərbaycan";
const SHELL_DESCRIPTION =
   "Azərbaycanın tarixi abidələri və mədəni irs xəritəsi. Bakı, Şəki, Qəbələ və digər bölgələrdəki 300+ abidəni kəşf edin. Viki Abidələri Sevir müsabiqəsinə şəkil yükləyin.";

const STATIC_PAGES = ["/", "/stats", "/leaderboard", "/table", "/about"];

interface MonumentFeature {
   type: "Feature";
   geometry: { type: "Point"; coordinates: [number, number] } | null;
   properties: Record<string, string>;
}

/** A sitemap URL expected to resolve to a prerendered file. */
interface ExpectedMonument {
   file: string;
   /** Title/og label after duplicate-label disambiguation (see prerender). */
   displayLabel: string;
}

const errors: string[] = [];

const fail = (message: string): void => {
   errors.push(message);
};

const attrValue = (tag: string, attr: string): string => {
   const match = tag.match(new RegExp(`${attr}="([^"]*)"`));
   return match ? match[1] : "";
};

const extractTitle = (html: string): string | null => {
   const match = html.match(/<title>([^<]*)<\/title>/);
   return match ? match[1] : null;
};

// Mirrors escapeHtml() in scripts/prerender.ts so expected titles compare
// against the escaped text the prerender writes into <title>.
const escapeHtmlText = (value: string): string =>
   value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const checkMonumentHtml = (
   html: string,
   loc: string,
   label: string,
   expectedDisplayLabel: string,
): void => {
   const expectedTitle = escapeHtmlText(`${expectedDisplayLabel} | ${SITE_TITLE}`);
   const title = extractTitle(html);
   if (!title) {
      fail(`${label}: missing <title>`);
   } else if (title === SITE_TITLE) {
      fail(`${label}: <title> is the default SPA shell title`);
   } else if (title !== expectedTitle) {
      fail(`${label}: <title> "${title}" != expected "${expectedTitle}"`);
   }

   const canonicalTags = html.match(/<link[^>]*rel="canonical"[^>]*>/g) || [];
   if (canonicalTags.length !== 1) {
      fail(`${label}: expected exactly 1 canonical link, found ${canonicalTags.length}`);
   } else if (attrValue(canonicalTags[0], "href") !== loc) {
      fail(
         `${label}: canonical href "${attrValue(canonicalTags[0], "href")}" != sitemap loc "${loc}"`,
      );
   }

   const descriptionTags = html.match(/<meta[^>]*name="description"[^>]*>/g) || [];
   if (descriptionTags.length !== 1) {
      fail(`${label}: expected exactly 1 description meta, found ${descriptionTags.length}`);
   } else {
      const content = attrValue(descriptionTags[0], "content");
      if (!content) {
         fail(`${label}: description meta is empty`);
      } else if (content === SHELL_DESCRIPTION) {
         fail(`${label}: description is the default SPA shell description`);
      }
   }

   const ogTitleTags = html.match(/<meta[^>]*property="og:title"[^>]*>/g) || [];
   if (ogTitleTags.length !== 1) {
      fail(`${label}: expected exactly 1 og:title, found ${ogTitleTags.length}`);
   } else {
      const expectedOgTitle = escapeHtmlText(expectedDisplayLabel);
      const ogTitle = attrValue(ogTitleTags[0], "content");
      if (ogTitle !== expectedOgTitle) {
         fail(`${label}: og:title "${ogTitle}" != expected "${expectedOgTitle}"`);
      }
   }

   const ogUrlTags = html.match(/<meta[^>]*property="og:url"[^>]*>/g) || [];
   if (ogUrlTags.length !== 1) {
      fail(`${label}: expected exactly 1 og:url, found ${ogUrlTags.length}`);
   } else if (attrValue(ogUrlTags[0], "content") !== loc) {
      fail(`${label}: og:url "${attrValue(ogUrlTags[0], "content")}" != sitemap loc "${loc}"`);
   }

   const jsonLdBlocks =
      html.match(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g) || [];
   if (jsonLdBlocks.length < 2) {
      fail(
         `${label}: expected >= 2 JSON-LD blocks (monument + breadcrumb), found ${jsonLdBlocks.length}`,
      );
   }
   for (const block of jsonLdBlocks) {
      const content =
         (block.match(/type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/) || [])[1] ?? "";
      try {
         const parsed = JSON.parse(content);
         if (!parsed || typeof parsed !== "object" || !parsed["@context"]) {
            fail(`${label}: JSON-LD block missing @context`);
         }
      } catch {
         fail(`${label}: JSON-LD block is not valid JSON`);
      }
   }

   if (!html.includes('id="seo-content"')) {
      fail(`${label}: missing #seo-content container`);
   }
   if (!/id="seo-content"[\s\S]*?<h1[\s>]/.test(html)) {
      fail(`${label}: #seo-content has no <h1>`);
   }

   const dataScript = html.match(/<script[^>]*id="monument-data"[^>]*>([\s\S]*?)<\/script>/);
   if (!dataScript) {
      fail(`${label}: missing #monument-data JSON block`);
   } else {
      try {
         const data = JSON.parse(dataScript[1]);
         if (!data || typeof data !== "object") {
            fail(`${label}: #monument-data is not a JSON object`);
         } else {
            const canonicalId = String(data.inventory ?? "")
               .split(",")[0]
               .trim();
            const expectedId = decodeURIComponent(loc.replace(`${HOST}/monument/`, ""));
            if (canonicalId !== expectedId) {
               fail(
                  `${label}: #monument-data inventory "${canonicalId}" != expected "${expectedId}"`,
               );
            }
            if (!data.itemLabel) {
               fail(`${label}: #monument-data missing itemLabel`);
            }
            // The embedded label is what the runtime head uses on the fast
            // path (the store is never initialized there) — it must match
            // the prerendered <title>/og:title rule.
            if (data.displayLabel !== expectedDisplayLabel) {
               fail(
                  `${label}: #monument-data displayLabel "${String(data.displayLabel)}" != expected "${expectedDisplayLabel}"`,
               );
            }
         }
      } catch {
         fail(`${label}: #monument-data is not valid JSON`);
      }
   }
};

const checkStaticHtml = (html: string, loc: string, label: string): void => {
   const title = extractTitle(html);
   if (!title) {
      fail(`${label}: missing <title>`);
   } else if (loc !== `${HOST}/` && title === SITE_TITLE) {
      // The homepage legitimately carries the site name as its title.
      fail(`${label}: <title> is the default SPA shell title`);
   }

   const canonicalTags = html.match(/<link[^>]*rel="canonical"[^>]*>/g) || [];
   if (canonicalTags.length !== 1) {
      fail(`${label}: expected exactly 1 canonical link, found ${canonicalTags.length}`);
   } else if (attrValue(canonicalTags[0], "href") !== loc) {
      fail(
         `${label}: canonical href "${attrValue(canonicalTags[0], "href")}" != sitemap loc "${loc}"`,
      );
   }

   const descriptionTags = html.match(/<meta[^>]*name="description"[^>]*>/g) || [];
   if (descriptionTags.length !== 1) {
      fail(`${label}: expected exactly 1 description meta, found ${descriptionTags.length}`);
   } else if (!attrValue(descriptionTags[0], "content")) {
      fail(`${label}: description meta is empty`);
   }
};

const main = async (): Promise<void> => {
   try {
      const geoData = JSON.parse(await fs.readFile(GEOJSON_PATH, "utf-8"));
      const features = geoData.features as MonumentFeature[];

      // Mirrors scripts/prerender.ts: only monuments with coordinates get a
      // static page, so only those are expected in the sitemap and dist.
      const locatedFeatures = features.filter((feature) => feature.geometry);
      // The page-bearing set (prerender skips empty inventories when writing
      // pages but counts all located features' labels — match exactly).
      const pageFeatures = locatedFeatures.filter((feature) =>
         (feature.properties.inventory || "").trim(),
      );
      // Same duplicate-label rule the prerender applied to <title>/og:title.
      const duplicateLabels = findDuplicateLabels(
         pageFeatures.map((feature) => feature.properties.itemLabel),
      );

      const monumentLocToFile = new Map<string, ExpectedMonument>();
      const locatedCanonicalIds = new Set<string>();
      for (const feature of locatedFeatures) {
         const rawInventory = feature.properties.inventory || "";
         if (!rawInventory) continue;
         const canonicalId = rawInventory.split(",")[0].trim();
         locatedCanonicalIds.add(canonicalId);
         const loc = `${HOST}/monument/${encodeIdForUrl(canonicalId)}`;
         monumentLocToFile.set(loc, {
            file: `${safeFileName(canonicalId)}.html`,
            displayLabel: getDisplayLabel(
               feature.properties.itemLabel,
               canonicalId,
               duplicateLabels,
            ),
         });
      }

      const expectedLocs = new Set<string>([
         `${HOST}/`,
         ...STATIC_PAGES.filter((r) => r !== "/").map((r) => `${HOST}${r}`),
         ...monumentLocToFile.keys(),
      ]);

      let sitemap: string;
      let robots: string;
      try {
         sitemap = await fs.readFile(SITEMAP_PATH, "utf-8");
         robots = await fs.readFile(ROBOTS_PATH, "utf-8");
      } catch {
         fail("sitemap.xml or robots.txt is missing — run the prerender step first");
         throw new Error("abort");
      }

      // --- Sitemap vs expected URLs (catches missing, extra, and duplicate entries) ---
      const sitemapLocs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
      const uniqueLocs = new Set(sitemapLocs);
      if (sitemapLocs.length !== uniqueLocs.size) {
         const dups = sitemapLocs.filter((l, i) => sitemapLocs.indexOf(l) !== i);
         fail(
            `sitemap has ${sitemapLocs.length - uniqueLocs.size} duplicate <loc> entries: ${[...new Set(dups)].join(", ")}`,
         );
      }
      const missing = [...expectedLocs].filter((loc) => !uniqueLocs.has(loc));
      const extra = [...uniqueLocs].filter((loc) => !expectedLocs.has(loc));
      if (missing.length) {
         fail(
            `sitemap is missing ${missing.length} expected URLs, e.g. ${missing.slice(0, 5).join(", ")}`,
         );
      }
      if (extra.length) {
         fail(`sitemap has ${extra.length} unexpected URLs, e.g. ${extra.slice(0, 5).join(", ")}`);
      }

      // --- Sitemap must not list IDs that404 (coord-less ids, non-first comma parts) ---
      const coordLessCanonicalIds = features
         .filter((f) => !f.geometry && (f.properties.inventory || "").trim())
         .map((f) => (f.properties.inventory || "").split(",")[0].trim());
      const nonFirstParts = new Set<string>();
      for (const feature of features) {
         const rawInventory = feature.properties.inventory || "";
         if (!rawInventory.trim()) continue;
         for (const part of rawInventory
            .split(",")
            .map((p) => p.trim())
            .slice(1)) {
            if (part) nonFirstParts.add(part);
         }
      }
      for (const id of new Set([...coordLessCanonicalIds, ...nonFirstParts])) {
         if (locatedCanonicalIds.has(id)) continue; // has a real page after all
         const loc = `${HOST}/monument/${encodeIdForUrl(id)}`;
         if (uniqueLocs.has(loc)) {
            fail(`sitemap lists URL that has no page (404s): ${loc}`);
         }
      }

      // --- URL -> file mapping for monument pages ---
      const existingFiles = new Set(await fs.readdir(MONUMENT_DIR));
      let checked = 0;
      const titleToLabel = new Map<string, string>();
      for (const [loc, expected] of monumentLocToFile) {
         const label = `monument ${loc.replace(`${HOST}/monument/`, "")}`;
         const filePath = path.join(MONUMENT_DIR, expected.file);
         let html: string;
         try {
            html = await fs.readFile(filePath, "utf-8");
         } catch {
            fail(`${label}: file ${expected.file} is missing`);
            continue;
         }
         checkMonumentHtml(html, loc, label, expected.displayLabel);

         // GSC duplicate-title cleanup: every page must ship a unique <title>.
         const title = extractTitle(html);
         if (title) {
            const clash = titleToLabel.get(title);
            if (clash) {
               fail(`duplicate <title> "${title}" shared by ${clash} and ${label}`);
            } else {
               titleToLabel.set(title, label);
            }
         }
         checked++;
      }

      // --- Orphaned monument files not present in the sitemap ---
      const expectedFiles = new Set(
         [...monumentLocToFile.values()].map((expected) => expected.file),
      );
      const orphans = [...existingFiles].filter((f) => !expectedFiles.has(f));
      if (orphans.length) {
         fail(
            `dist/monument has ${orphans.length} orphan file(s) not in the sitemap: ${orphans.slice(0, 5).join(", ")}`,
         );
      }

      // --- Static pages ---
      for (const route of STATIC_PAGES) {
         const loc = `${HOST}${route}`;
         const fileName = route === "/" ? "index.html" : `${route.slice(1)}.html`;
         const label = `static ${loc}`;
         let html: string;
         try {
            html = await fs.readFile(path.join(DIST_DIR, fileName), "utf-8");
         } catch {
            fail(`${label}: file ${fileName} is missing`);
            continue;
         }
         checkStaticHtml(html, loc, label);
      }

      // --- robots.txt ---
      if (!robots.includes(`Sitemap: ${HOST}/sitemap.xml`)) {
         fail("robots.txt is missing the sitemap declaration");
      }
      if (!robots.includes("Disallow: /*?*inventory=")) {
         fail("robots.txt is missing the ?inventory= disallow rule");
      }

      // --- Generated nginx redirect map (non-first comma parts -> canonical) ---
      let redirectConf = "";
      try {
         redirectConf = await fs.readFile(REDIRECTS_PATH, "utf-8");
      } catch {
         fail("monument-redirects.conf is missing — run the prerender step first");
      }

      const actualRedirects = new Map<string, string>();
      for (const match of redirectConf.matchAll(
         /^location = \/monument\/(.+) \{ return 301 \/monument\/(.+); \}$/gm,
      )) {
         const [, source, target] = match;
         if (actualRedirects.has(source)) {
            fail(`redirect map has duplicate entries for /monument/${source}`);
         } else {
            actualRedirects.set(source, target);
         }
      }

      const expectedRedirects = new Map<string, string>();
      for (const feature of pageFeatures) {
         const parts = (feature.properties.inventory || "").split(",").map((p) => p.trim());
         const canonicalId = parts[0];
         for (const source of parts.slice(1)) {
            // Mirrors buildRedirectConf in scripts/prerender.ts.
            if (!source || source === canonicalId || locatedCanonicalIds.has(source)) continue;
            expectedRedirects.set(source, encodeIdForUrl(canonicalId));
         }
      }
      for (const [source, target] of expectedRedirects) {
         const actual = actualRedirects.get(source);
         if (actual === undefined) {
            fail(`redirect map missing /monument/${source} -> /monument/${target}`);
         } else if (actual !== target) {
            fail(`redirect /monument/${source} targets "${actual}", expected "${target}"`);
         }
      }
      for (const source of actualRedirects.keys()) {
         if (locatedCanonicalIds.has(source)) {
            fail(`redirect source /monument/${source} shadows an existing monument page`);
         } else if (!expectedRedirects.has(source)) {
            fail(`redirect map has unexpected source /monument/${source}`);
         }
      }

      // --- nginx.conf wiring (404 behavior + redirect include) ---
      try {
         const nginxConf = await fs.readFile(NGINX_CONF_PATH, "utf-8");
         if (!nginxConf.includes("include /var/www/wlmaz/monument-redirects.conf;")) {
            fail("nginx.conf does not include /var/www/wlmaz/monument-redirects.conf");
         }
         if (!/location \/monument\/\s*\{[^}]*try_files \$uri \$uri\.html =404/.test(nginxConf)) {
            fail("nginx.conf /monument/ location must serve via `try_files $uri $uri.html =404`");
         }
      } catch {
         fail("nginx.conf is missing");
      }

      if (errors.length) {
         console.error(`HTML verification FAILED with ${errors.length} issue(s):`);
         for (const error of errors) {
            console.error(`  - ${error}`);
         }
         process.exit(1);
      }

      console.log(
         `HTML verification passed: ${checked} monument pages, ${STATIC_PAGES.length} static pages, sitemap (${sitemapLocs.length} URLs), ${actualRedirects.size} redirects, robots.txt`,
      );
   } catch (error) {
      if (error instanceof Error && error.message === "abort") {
         process.exit(1);
      }
      console.error("HTML verification failed:", error);
      process.exit(1);
   }
};

main();
