import { library } from "@fortawesome/fontawesome-svg-core";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { faCopyright, faImage } from "@fortawesome/free-regular-svg-icons";
/* import specific icons */
import {
   faArrowLeft,
   faBan,
   faBars,
   faCamera,
   faChartLine,
   faChartPie,
   faCheck,
   faCircleInfo,
   faCircleNotch,
   faCloudArrowUp,
   faExclamationTriangle,
   faExternalLinkAlt,
   faFileSignature,
   faInfo,
   faInfoCircle,
   faLandmark,
   faLayerGroup,
   faList,
   faLocationArrow,
   faMapLocationDot,
   faMapMarkedAlt,
   faPenToSquare,
   faPlus,
   faSignInAlt,
   faSortNumericDown,
   faSpinner,
   faUser,
   faUserCircle,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* add icons to the library */
library.add(
   faArrowLeft,
   faBan,
   faBars,
   faCamera,
   faChartLine,
   faChartPie,
   faCheck,
   faCircleInfo,
   faCircleNotch,
   faCloudArrowUp,
   faExclamationTriangle,
   faExternalLinkAlt,
   faFileSignature,
   faInfo,
   faInfoCircle,
   faLandmark,
   faLayerGroup,
   faList,
   faLocationArrow,
   faMapLocationDot,
   faMapMarkedAlt,
   faPenToSquare,
   faPlus,
   faSignInAlt,
   faSortNumericDown,
   faSpinner,
   faUser,
   faUserCircle,
   faCopyright,
   faImage,
   faGithub,
);

export { FontAwesomeIcon };
